vector-engineering/covidcg

package-lock.json
package.json
src/components/LoadingScreen.js

fade in on the splash screen

---

src/components/Pages/ExampleTab.js
src/components/Pages/GroupTab.js
src/components/Pages/HomePage.js
src/components/Pages/LocationTab.js
src/components/Pages/SequencingEffortsTab.js
src/components/Sidebar/CoordinateSelect.js
src/components/Vega/AppStatusBox.js
src/stores/asyncDataStore.js

Add box describing status of selected sequences and current filters. 
Also fix some UI bugs

Status box (dynamic footnote)

---

config/config_gisaid_private.yaml
package-lock.json
src/utils/downloads/downloadAggCaseData.js
src/utils/version.js

Fix offset in NT SNV positions when downloading aggregate table data from lineages/clades

---

services/server/cg_server/main.py
src/components/Legend/TableLegend.js
src/components/Modals/SelectSequencesModal.js
src/components/Modals/SelectSequencesModal.styles.js
src/components/Pages/HomePage.js
src/components/Selection/CoordinateSelect.js
src/components/Selection/DateSelect.js
src/components/Selection/FilterDataIntoOther.js
src/components/Selection/GroupBySelect.js
src/components/Selection/LocationSelect.js
src/components/Selection/LocationSelect.styles.js
src/components/Selection/MetaFieldSelect.js
src/stores/configStore.js
src/stores/locationData.js
src/utils/location.js
src/utils/version.js

Not sure if I entirely like this new behavior, but not sure how we would get it to work otherwise
Closes #160

Location selections

---

services/server/cg_server/main.py
services/server/cg_server/query.py
src/components/Pages/ExampleTab.js
src/components/Vega/GlobalSeqPlot.js
src/components/Vega/SurveillancePlot.js
src/stores/dataStore.js
src/utils/snpData.worker.js

Data fixes + some small UI tweaks

Fixes for v2.0.0-rc1

---

.gitignore
build/build.sh
build/deploy.sh
package.json
src/utils/version.js

* Adjust deployment scripts
* Sentry error monitoring

V2 hotfix 6

---

package-lock.json
src/components/Common/TabIndicator.js
src/components/Selection/CoordinateSelect.js
src/components/Sidebar/TabBar.js
src/constants/defs.json
src/stores/UIStore.js
src/stores/configStore.js
src/utils/gene_protein.js
src/utils/reference.js
src/utils/updateQueryParam.js

Adds support for degenerate nucleotides and setting config values to and from the url

URL Params and Degenerate NTs

---

src/components/Vega/GroupStackPlot.js
src/stores/configStore.js
src/stores/dataStore.js

- Fixes global sequencing map download
- Fixes location-date plot download (#306)

Download fixes

---

src/routes.js
src/stores/dataStore.js
src/stores/rootStore.js

https://sentry.io/organizations/vector-engineering/issues/2305105219/?project=5697727&query=is%3Aunresolved

fix Cannot read property 'onCaseDataStateStarted' of undefined

---

.gitignore
README.md
environment.yml

Improve pipeline documentation and fix installation issue with snakemake

Pipeline docs + installation

---

services/server/cg_server/main.py
services/server/cg_server/query/__init__.py
services/server/cg_server/query/group_snv_frequencies.py
src/components/Modals/DownloadConsensusMutationsModal.js
src/components/Modals/DownloadConsensusMutationsModal.styles.js
src/components/Sidebar/StatusBox.js
src/stores/UIStore.js
src/stores/configStore.js
src/stores/connect.js
src/stores/groupDataStore.js
src/stores/rootStore.js

Download consensus mutations for phylogenetic definitions (i.e., lineages, clades)

Download Group Consensus Mutations

---

environment.yml
workflow_genbank_ingest/Snakefile
workflow_genbank_ingest/envs/pangolin.yaml
workflow_genbank_ingest/scripts/chunk_data.py
workflow_genbank_ingest/scripts/download.py
workflow_main/Snakefile

* Fix max size error when loading in new genbank data
* Update pangolin to 3.1.4
* Fix bugs in main workflow

Genbank fixes

---

package-lock.json
package.json
src/components/GroupReport/GroupStructuralViewer.js
src/components/GroupReport/MutationList.js
src/components/Pages/CompareGroupsTab.js
src/components/Selection/CoordinateSelect.js
src/components/Vega/GroupTreePlot.js
src/stores/groupDataStore.js
src/utils/version.js

* Various bug fixes for report tab

2.1.0 beta2

---

README.md

Added POSTGRES_MAX_CONN and a brief description of the variable to the README under PostrgreSQL in the per-service installation section. Could not find other documentation where adding the note would be necessary

Updated README to include setting POSTGRES_MAX_CONN

---

src/components/Selection/LocationItem.js
src/components/Selection/LocationItem.styles.js
src/components/Selection/LocationSelect.js
src/components/Selection/LocationSelect.styles.js
src/components/Sidebar/FilterSidebar.js

Add separate location items

---

src/components/Vega/GroupStackPlot.js
src/components/Vega/LowFreqFilter.js
src/stores/plotSettingsStore.js
src/utils/data.js

Fix low freq count collapse in group stack plot

---

environment.yml
workflow_main/Snakefile
workflow_main/analyses/Snakefile
workflow_main/scripts/extract_dna_snps.py
workflow_main/scripts/read_extractor_lite.py
workflow_main/scripts/util.py

Switch alignment tool to minimap2 – it's much faster and yields similar results (only differences I have seen are at the 3' and 5' UTRs – which is not as important)

Bowtie2 to Minimap2

---

src/components/GroupReport/GroupReportHeader.js
src/components/GroupReport/GroupSearch.js
src/components/GroupReport/MutationList.js
src/components/GroupReport/OrgLegend.js
src/components/GroupReport/VOCList.js

Fixes linter issues for GroupReport tab

Fixed linter issues

---

src/components/GroupReport/MutationList.js
src/components/GroupReport/MutationList.styles.js

Hide protein checkbox and MutationListTableHeader remain at the top of the MutationList when scrolling vertically.

Mutation list scroll

---

src/components/GroupReport/OrgLegend.js
src/components/GroupReport/OrgLegend.styles.js

OrgLegend contains ExternalLinks to each organization

OrgLegend now links to variant page for each organization

---

src/components/GroupReport/OrgLegend.js
src/components/GroupReport/VOCList.js
src/components/Pages/GroupReportTab.js
src/components/Vega/EntropyPlot.js
static_data/CDC.json
static_data/ECDC.json
static_data/PHE.json
static_data/WHO.json
static_data/vocs.json
workflow_main/Snakefile
workflow_main/analyses/Snakefile
workflow_main/phylotree/Snakefile
workflow_main/scripts/get_cdc_vocs.py
workflow_main/scripts/get_ecdc_vocs.py
workflow_main/scripts/get_phe_vocs.py

PHE website scraped and VOCList/Snakefile updated to include those variants

Add PHE variants

---

src/components/Pages/AboutTab.js
src/components/Sidebar/TabBar.js
src/constants/defs.json

About Tab updated for first anniversary according to Alina's Google Doc,

Updated About Tab

---

src/components/LoadingScreen.js
src/stores/groupDataStore.js

Added AY.4 as a default selected lineage in `src/stores/groupDataStore.js` however it is worth noting that AY4 doesn't show up on either the live site or the dev site,. #405

Added AY.4 as a default selected lineage

---

static_data/CDC.json
static_data/ECDC.json
static_data/WHO.json
static_data/vocs.json
workflow_main/Snakefile
workflow_main/scripts/get_cdc_vocs.py
workflow_main/scripts/get_who_vocs.py

The webscraper rule now requires a daily ".done" file to exist in the data_folder. Also includes updates to the CDC and WHO webscrapers as they have updated their layouts slightly

Scrape for VOCs/VOIs Daily

---

src/components/Vega/EntropyPlot.js

Fixed Entropy plot linter issues

---

workflow_main/scripts/get_cdc_vocs.py

The CDC pushed a big change to their variants page changing the url, class names, but is still inconsistent with their data entry. This scraper reads the current CDC variants page and cleans up the data.

Updated to new CDC formatting

---

package-lock.json
package.json
src/components/GroupReport/MutationList.js
src/components/Pages/MethodologyTab.js
src/utils/version.js

Small fixes left out from prev patch

V2.4.4 additional

---

src/components/Sidebar/TabBar.js

Ben requested a different tab order to match the manuscript. (Home, Lineage Reports, Compare Mutations/Locations, ...)
closes #486

Changed TabBar tab order

---

src/components/Common/TabIndicator.styles.js
src/components/Legend/Legend.js
src/components/Modals/SelectSequencesModal.js
src/components/Pages/HomePage.js
src/components/Pages/HomePage.styles.js
src/components/Selection/GroupBySelect.js
src/components/Selection/GroupBySelect.styles.js
src/components/Selection/SelectionTopBar.js
src/components/Selection/SelectionTopBar.styles.js
src/components/Sidebar/DownloadDataButton.js
src/components/Sidebar/DownloadDataButton.styles.js
src/components/Sidebar/FilterSidebar.js
src/components/Sidebar/FilterSidebar.styles.js
src/components/Sidebar/StatusBox.js
src/components/Sidebar/StatusBox.styles.js
src/stores/dataStore.js

Closes #473 
Closes #474 
Closes #472

New select UI

---

src/vega_specs/group_stack.vg.json
src/vega_specs/group_stack_standalone.vg.json
src/vega_specs/location_date.vg.json
src/vega_specs/location_date_standalone.vg.json
src/vega_specs/surveillance.vg.json

Added vega logic to relevant plots which colors the background of the plots by year.

Vega year update

---

src/components/Example/WalkthroughList.js
src/components/Example/WalkthroughList.styles.js
src/components/Example/examples.js
src/components/Pages/HomeTab.js

- Add walkthrough cards to homepage
- Add walkthrough analyses as examples

Add Broad Retreat walkthroughs

---

src/components/GroupReport/VOCList.styles.js

Reverses the arrow direction in for VOCList

Reversed arrow direction

---

API.md
services/server/cg_server/query/group_mutation_frequencies.py
services/server/cg_server/routes/query.py

Adding new API route at `/group_mutation_frequencies_dynamic`
Partially addresses #437

Dynamic Group Mutation Frequencies

---

src/constants/colors.js

Expands the number of colors present when displaying mutations

Added Paul Tol light scheme to mutation color palette

---

src/components/Common/LineageName.js
src/components/Common/LineageName.styles.js
src/components/GroupReport/VOCList.js
src/components/GroupReport/VOCList.styles.js
src/components/Legend/TableLegendItem.js
workflow_main/scripts/get_who_vocs.py
workflow_main/scripts/update_vocs.py

Updated VOCList footnote, added WHO label (if any) to each variant in the sidebar legend when in lineage mode and to each cell in the Lineage Reports tab at all times.

Who labels

---

workflow_main/scripts/get_who_vocs.py

Updated Webscraper to match WHO's new VOC table layout

WHO shuffled their variant table columns, updated webscraper

---

workflow_main/scripts/read_extractor_lite.py

Remove long insertions containing degenerate/non-canonical NTs

---

src/components/Example/WalkthroughList.styles.js
src/components/Pages/CompareGroupsTab.js
src/components/Sidebar/StatusBox.js
src/components/Vega/GroupStackPlot.js
src/utils/mutationData.worker.js

Add location selection dropdown on GroupStack plot

---

package-lock.json
package.json
src/components/Modals/DownloadPymolScriptModal.js
src/components/Modals/SelectSequencesModal.js
src/components/Selection/CoordinateSelect.js
src/components/Viz/EntropyPlot.js
src/components/Viz/MutationStructureViewer.js
src/constants/initialValues.js
src/utils/reference.js
src/utils/version.js

Still a lot of issues to iron out from the multiple reference switch

RSV dev 8 release

---

build/build.sh
config/config_sars2_genbank.yaml
config/config_sars2_gisaid.yaml
config/config_sars2_gisaid_private.yaml
workflow_sars2_genbank_ingest/Snakefile
workflow_sars2_gisaid_ingest/Snakefile
workflow_sars2_gisaid_ingest/scripts/process_feed.py

Bug fixes for SARS2 GISAID workflow

SARS2 workflow fixes

---

README.md
workflow_main/Snakefile
workflow_main/analyses/Snakefile
workflow_main/analyses/scripts/standalone_map_spec.py
workflow_main/scripts/bam_subseq.py
workflow_main/scripts/read_extractor_lite.py

- Pull spike NT and AA sequences from each sequence
- Base functionality: extract arbitrary subsequences from BAM alignments

Spikenuc extraction

---

package-lock.json
package.json

Reverts vector-engineering/covidcg#579

Revert "Bump loader-utils and html-webpack-plugin"

---

README.md
build/deploy.sh
config/config_flu_genbank.yaml
config/config_flu_gisaid.yaml
config/config_rsv_custom.yaml
config/config_rsv_genbank.yaml
config/config_sars2_alpha.yaml
config/config_sars2_custom.yaml
config/config_sars2_genbank.yaml
config/config_sars2_genbank_dev.yaml
config/config_sars2_gisaid.yaml
config/config_sars2_gisaid_private.yaml
package-lock.json
package.json
services/server/cg_server/app.py
src/components/Common/AcknowledgementFooter.js
src/components/GroupReport/GroupStructuralViewer.js
src/components/GroupReport/MutationList.js
src/components/Selection/SelectionTopBar.js
src/components/Viz/EntropyPlot.js
src/components/Viz/GroupTreePlot.js
src/config/index.js
src/utils/version.js
src/vega_specs/group_tree_legend_v2.vg.json
src/vega_specs/group_tree_v2.vg.json
static_data/flu/genes_processed.json
static_data/flu/proteins_processed.json
workflow_main/Snakefile

v2.7.0-rc7 polish

---

services/server/cg_server/db_seed/seed.py
services/server/cg_server/query/selection.py
src/components/Selection/GroupBySelect.js
src/components/Selection/SelectionTopBar.js
src/components/Selection/SelectionTopBar.styles.js
src/components/Sidebar/DownloadDataButton.js
src/components/Viz/EntropyPlot.js
workflow_main/scripts/combine_coverage_pivot.py

Refactor coverage tables in the database for faster querying

Coverage DB refactor

---

src/vega_specs/global_seq_v2.vg.json
workflow_flu_gisaid_ingest/README.md
workflow_main/Snakefile

Hotfix v2.7.2

---

config/config_flu_gisaid.yaml
workflow_flu_gisaid_ingest/Snakefile
workflow_flu_gisaid_ingest/scripts/clean_metadata.py
workflow_main/scripts/extract_aa_mutations.py

- Misc. fixes to accomodate new data

Flu workflow fixes

---

.gitignore
environment.yml
environment_osx-arm64.yml
workflow_main/scripts/send_email.py

Add script to send emails upon data pipeline completion/failure. Closes #416

Pipeline email script

---

package-lock.json

Reverts vector-engineering/covidcg#608

Revert "Bump vega-functions from 5.13.0 to 5.13.1"

---

src/components/Viz/SurveillancePlot.js
src/examples/examples.rsv.js

Update copy on the RSV site homepage (surv plot, examples)

Update RSV copy

---

build/build.sh
build/deploy.sh
config/config_flu_genbank.yaml
config/config_flu_genbank_dev.yaml
config/config_flu_gisaid.yaml
config/config_flu_gisaid_dev.yaml
config/config_rsv_custom.yaml
config/config_rsv_genbank.yaml
config/config_sars2_alpha.yaml
config/config_sars2_custom.yaml
config/config_sars2_genbank.yaml
config/config_sars2_genbank_dev.yaml
config/config_sars2_gisaid.yaml
config/config_sars2_gisaid_6month.yaml
config/config_sars2_gisaid_private.yaml
docker-compose.flu.genbank.yml
services/server/cg_server/db_seed/seed.py
workflow_flu_genbank_ingest/Snakefile
workflow_flu_genbank_ingest/scripts/chunk_sequences.py
workflow_flu_genbank_ingest/scripts/clean_metadata.py
workflow_flu_genbank_ingest/scripts/sequence_quality.py
workflow_flu_genbank_ingest/scripts/write_ha_fasta.py
workflow_main/scripts/sequence_manifest.py

Final touches on the Flu GenBank site

Flu Genbank release

---

.gitignore
workflow_main/scripts/extract_aa_mutations.py

Tolerate frameshifting indels as long as they are resolved within 10 codons
Also simplified the mutation code slightly - hopefully the algorithm is more readable now

Tolerate frameshifting indels as long as they are resolved

---

workflow_flu_genbank_ingest/Snakefile
workflow_flu_genbank_ingest/scripts/download_metadata.py
workflow_flu_genbank_ingest/scripts/download_sequences.py
workflow_rsv_genbank_ingest/Snakefile
workflow_rsv_genbank_ingest/scripts/download_metadata.py
workflow_rsv_genbank_ingest/scripts/download_sequences.py
workflow_sars2_genbank_ingest/Snakefile
workflow_sars2_genbank_ingest/scripts/download_metadata.py
workflow_sars2_genbank_ingest/scripts/download_sequences.py

Fix some crashes relating to date ranges in GenBank sites

Date cutoff fixes for GenBank pipelines

---

workflow_main/scripts/send_email.py
workflow_sars2_genbank_ingest/scripts/clean_metadata.py

Quick fix for header rows sneaking into genbank metadata

250813 Genbank metadata hotfix
