vector-engineering/covidcg

workflow_genbank_ingest/Snakefile

When running the Genbank ingest version of the pipeline I ran into the following error:
```
InputFunctionException in line 116 of /home/CSCScience.ca/apetkau/workspace/covidcg-1.4/workflow_genbank_ingest/Snakefile:
Error:
NameError: name 'gzip' is not defined
Wildcards:
Traceback:
File "/home/CSCScience.ca/apetkau/workspace/covidcg-1.4/workflow_genbank_ingest/Snakefile", line 105, in get_changed_chunks
File "/home/CSCScience.ca/apetkau/workspace/covidcg-1.4/workflow_genbank_ingest/Snakefile", line 70, in get_num_seqs
Removing output files of failed job chunk_data since they might be corrupted:
../data_genbank/fasta_temp, ../data_genbank/metadata_dirty.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
Adding `import gzip` …

Added gzip library

---

environment.yml
workflow_main/scripts/write_reference_files.py

This makes two small changes to get the **workflow_main** snakemake workflow working properly.
1. I ran into an issue when running where **samtools** was missing. It is currently being used here https://github.com/vector-engineering/covidcg/blob/093512e62ddca589c454debb18d923e4133ab1d7/workflow_main/Snakefile#L109 but was not included in the `environment.yml` so I added it.
2. In one of the dependency scripts I ran into an issue where it could not find the `read_fasta_file` function so I added an import statement.

Fixed up import/added samtools dependency

---

package-lock.json
package.json
src/components/App.js
src/components/Pages/HomePage.js
src/components/Vega/GlobalSeqPlot.js
src/components/Vega/SurveillancePlot.js
src/index.js
webpack.config.dev.js
webpack.config.prod.js

this gets rid of react hot loader, it was broken anyways so we can re-enable it in the future
before
after

clean bundle

---

src/vega_specs/group_stack.vg.json
src/vega_specs/group_stack_standalone.vg.json
src/vega_specs/location_date.vg.json
src/vega_specs/location_date_standalone.vg.json

GroupStack and LocationDate now have a limited number of ticks on their x-axis, which adjust automatically depending on user input. In addition, changed the format of the GroupStack datetime labels so that only one label is given per date

Updated GroupStack and LocationDate to adjust x-axis

---

services/server/cg_server/main.py
services/server/cg_server/query/__init__.py
services/server/cg_server/query/report.py
services/server/cg_server/query/selection.py
services/server/requirements.txt

Generate a Spike mutation and lineage report
This report will consist of:
1) Single Spike SNV frequencies, both global and regional
2) Co-occurring Spike SNV frequencies, both global and regional
3) PANGO lineage frequencies, both global and regional
Fetch the more complex data (regional data) from the database,
and then from this compute the global counts in python.
Format the regional tables as pivot tables, and do this in python,
since crosstab() in Postgres makes me sad
Start and end dates are passed via. URL query params
Download the full excel file with:
curl http://[host]/az_report?start_date=YYYY-MM-DD&end_date=YYYY-MM-DD -o out.xlsx
Dates are in ISO format "YYYY-MM-DD"

Add AZ report endpoint

---

src/components/LoadingScreen.js

SVG uses OS font, changing to png standardizes font.

Converted logo from svg to png

---

workflow_rsv_genbank_ingest/scripts/chunk_data.py

Sequences from before 1996 (the year the rsv reference was published) are downloaded from genbank but are not chunked into the fasta_raw/fasta_temp folders.

RSVG Ingest Date Cutoff

---

src/components/Buttons/QuestionButton.js
src/components/Example/examples.js

Fixes the global lineage example by providing selectTree.children instead of just selectedTree. Also fixes linter issues with QuestionButtonContainer (provides an empty array for useEffect so that it is only called after mount and changes rebuild proptype to string)

Example fix

---

workflow_main/scripts/get_ecdc_vocs.py

The ECDC added a few invisible cells after adding omicron to their VOC tables which broke the webscraper. The ECDC webscraper has been updated to work both with the invisible td cells and in the case that they remove the cells at some point in the near future.

Updated for new layout after omicron

---

src/components/Vega/EntropyPlot.js
src/vega_specs/entropy.vg.json
workflow_main/scripts/get_cdc_vocs.py

The infinite loop in the primer domain plot was caused by a case where primersInRow is empty. A case was added for when primersInRow is empty. In addition, a separate function was made to handle displaying primers in the domain plot rather than having one function for primer and non-primer coordinate modes. This was tested with all primers selected, no primers selected, and random groups of primers selected and worked locally in all cases.
In addition, the vega specs were updated so that the click and drag selection height and domain bar heights update with the plot.

Domain plot fix

---

src/components/GroupReport/OrgLegend.js
src/components/Pages/GroupReportTab.js

Displays UKHSA instead of PHE in the Lineage Reports Tab. Other logic surrounding the PHE name is unchanged

OrgLegend now displays UKHSA instead of PHE

---

src/components/GroupReport/GroupReportHeader.js
src/components/GroupReport/VOCList.js
src/components/GroupReport/VOCList.styles.js

Changed from a column list of VOCs to a table with expandable rows:

VOC Overflow Fix

---

src/components/Modals/SelectSequencesModal.js

The async nature of useState meant that changes made by changing selected locations would overwrite changes made by the coordinate selection logic. This pr separates pending changes by their category before stitching them together with a useEffect hook when the states have been updated.

Seperated pending changes by category

---

services/server/cg_server/query/group_mutation_frequencies.py
src/components/GroupReport/MutationList.js
src/utils/mutationUtils.js

- Translate stop codon from "_" to more conventional "*"
- For deletions, format as ∆[ref][pos]. i.e., F13- --> ∆F13
- For insertions, remove ref '-'. i.e., -13F --> 13F
Underlying data downloads remain unchanged (to prevent messing up existing dependent tools)

More conventional mutation formatting

---

config/config_flu_genbank.yaml
config/config_rsv_genbank.yaml
config/config_sars2_genbank.yaml
config/config_sars2_genbank_dev.yaml
workflow_flu_genbank_ingest/Snakefile
workflow_flu_genbank_ingest/scripts/download.py
workflow_rsv_genbank_ingest/Snakefile
workflow_rsv_genbank_ingest/scripts/download.py
workflow_sars2_genbank_ingest/Snakefile
workflow_sars2_genbank_ingest/scripts/download.py

Current downloads for SARS2 on the NCBI Virus endpoint are timing out due to large data size. This PR chunks out downloads by a user-configurable period and combines chunks to feed into existing ingest workflows.

Chunk GenBank (NCBI Virus vvsearch) downloads

---

workflow_sars2_gisaid_ingest/Snakefile
workflow_sars2_gisaid_ingest/scripts/process_feed.py

Decompress the feed.json.xz file as a stream in `process_feed.py` instead of storing the plaintext JSON on disk -- it was exceeding hundreds of GB

Uncompress SARS2 feed file on the fly to save disk space

---

config/config_sars2_gisaid.yaml
config/config_sars2_gisaid_private.yaml
package-lock.json
package.json
src/utils/version.js
workflow_main/Snakefile
workflow_main/scripts/preprocess_sars2_sequences.py
workflow_sars2_genbank_ingest/Snakefile
workflow_sars2_gisaid_ingest/Snakefile
workflow_sars2_gisaid_ingest/envs/pangolin.yaml
workflow_sars2_gisaid_ingest/scripts/clean_metadata.py
workflow_sars2_gisaid_ingest/scripts/process_feed.py

- Add PANGO annotations, in place of GISAID's own annotations
- Rename GISAID's annotations to "gisaid_lineage", and preferentially use our own PANGO lineage designations
Any missing designations from our own annotations will be backfilled with GISAID's calls.

PANGO annotations for SARS2 GISAID workflow

---

.gitignore
config/config_flu_genbank.yaml
config/config_flu_gisaid.yaml
config/config_flu_gisaid_dev.yaml
config/config_rsv_custom.yaml
config/config_rsv_genbank.yaml
config/config_sars2_alpha.yaml
config/config_sars2_custom.yaml
config/config_sars2_genbank.yaml
config/config_sars2_genbank_dev.yaml
config/config_sars2_gisaid_6month.yaml
config/config_sars2_gisaid_private.yaml
services/server/cg_server/db_seed/seed.py
workflow_main/Snakefile
workflow_main/scripts/sequence_manifest.py

Add configuration option to truncate sequences in the main pipeline. Useful for creating date-limited datasets or to optimize pipeline running time (currently >24 hours for all SARS2 data)

Truncated main workflow

---

src/vega_specs/surveillance.vg.json
src/vega_specs/surveillance_standalone_rsv.vg.json

Current surveillance plot linearly interprets across missing values. Fix this to show percentages of 0 when no data is available.

Fix: fill missing surveillance counts with 0 instead of lirping between known values

---

workflow_flu_genbank_ingest/scripts/download_metadata.py
workflow_flu_genbank_ingest/scripts/download_sequences.py
workflow_rsv_genbank_ingest/scripts/download_metadata.py
workflow_rsv_genbank_ingest/scripts/download_sequences.py
workflow_sars2_genbank_ingest/scripts/download_metadata.py
workflow_sars2_genbank_ingest/scripts/download_sequences.py

Previous GenBank download requests had malformed datetime strings when one date exceeded the maximum date (current date)

Fix GenBank date format in ingest download reqs

---

src/utils/mutationUtils.js
workflow_main/scripts/build_full_dataframe.py
workflow_main/scripts/extract_aa_mutations.py
workflow_main/scripts/process_mutations.py

In the CSV data files themselves:
- Multiple deletions will be split up into single deletions
- ∆HV69 → ∆H69, ∆V70
- Mutations will be “ungrouped” if possible
- FR157SG → F157S, R158G
- Add `positions_affected` columns to `data_complete.csv` file, for easier searching of positions affected by mutations
- For example, for sequence containing LPPA24S, positions 24, 25, 26, 27 are added to a list in a separate column.
On the website (UI changes only)
- Large mutations with coupled insertions/mutations (where the mutation site is not obvious) will be labeled with the position range rather than a simple position
- LPPA24S → LPPA24/27S

Mutation separation

---

docker-compose.cloudsql.prod.yml
docker-compose.cloudsql.yml
docker-compose.flu.genbank.yml
docker-compose.flu.gisaid.yml
docker-compose.rsv.yml
docker-compose.sars2.yml
docker-compose.yml
services/server/cg_server/download/metadata.py
services/server/cg_server/query/group_mutation_frequencies.py
services/server/cg_server/query/report.py
services/server/cg_server/query/variant_table.py
src/stores/dataStore.js

Fixes bugs that were preventing sequence and variant table downloads

Flu download fix

---

build/build.sh
workflow_flu_genbank_ingest/scripts/clean_metadata.py

Data contamination in segment metadata was causing crashes - this fixes those errors

Flu genbank - sanitize segment metadata before integer casting
